# Generated by Django 4.0.6 on 2022-09-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='studentPayment',
            new_name='student',
        ),
    ]
