# Generated by Django 4.0.6 on 2022-09-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_studentpayment_payment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.IntegerField(max_length=200),
        ),
    ]
