# Generated by Django 4.0.6 on 2022-09-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lesson_count_alter_teachers_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='count',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
